ALTER TABLE products
    ADD COLUMN IF NOT EXISTS description TEXT,
    ADD COLUMN IF NOT EXISTS sku VARCHAR(255),
    ADD COLUMN IF NOT EXISTS cost_price NUMERIC(38,2),
    ADD COLUMN IF NOT EXISTS active BOOLEAN DEFAULT TRUE NOT NULL,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP(6),
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP(6);

ALTER TABLE products
    ADD CONSTRAINT uc_products_sku UNIQUE (sku);

ALTER TABLE categories
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP(6),
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP(6);

ALTER TABLE carts
    ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'OPEN' NOT NULL;

ALTER TABLE inventory_transactions
    ADD COLUMN IF NOT EXISTS reference_id BIGINT;

UPDATE products SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL;
UPDATE categories SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL;